apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: mx-build-task
spec:
  params:
    - name: APP_NAME
      type: string
    - name: NPM_TOKEN
      type: string
  stepTemplate:
    env:
      - name: NPM_CONFIG_USERCONFIG
        value: /tekton/home/npm/.npmrc
      - name: HOME
        value: /tekton/home
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 500m
        memory: 1000Mi
    workingDir: /workspace/source
  steps:
    # https://github.com/jenkins-x/jx3-pipeline-catalog/blob/master/tasks/git-clone/git-clone-pr.yaml
    - name: ''
      image: uses:jenkins-x/jx3-pipeline-catalog/tasks/git-clone/git-clone-pr.yaml@versionStream

    - name: apply-secret
      image: bitnami/kubectl:latest
      script: |
        echo "
        apiVersion: 'kubernetes-client.io/v1'
        kind: ExternalSecret
        metadata:
          name: build-$(params.APP_NAME)
        spec:
          backendType: vault
          vaultMountPoint: 'kubernetes'
          vaultRole: 'jx-vault'
          dataFrom:
            - 'io/data/rewardops/jx/preview/$(params.APP_NAME)'
        " | kubectl apply -f -

    # https://github.com/jenkins-x/jx (1 of 3 artifacts)
    - name: jx-variables
      image: ghcr.io/jenkins-x/jx-boot:3.10.86
      script: |
        #!/usr/bin/env sh
        jx gitops variables 
        jx gitops pr variables
        sed -i 's/^export APP_NAME=.*/export APP_NAME="$(params.APP_NAME)"/' /workspace/source/.jx/variables.sh

    # https://github.com/jenkins-x-plugins/jx-registry
    - name: jx-registry
      image: ghcr.io/jenkins-x/jx-registry:0.1.10
      env:
        - name: CACHE_SUFFIX
          value: '/cache'
        - name: ECR_LIFECYCLE_POLICY
          value: |-
            {
              "rules": [
                {
                  "rulePriority": 1,
                  "description": "Expire images older than 180 days",
                  "selection": {
                    "tagStatus": "tagged",
                    "countType": "sinceImagePushed",
                    "tagPrefixList": ["0.0.0-"],
                    "countUnit": "days",
                    "countNumber": 180
                  },
                  "action": {
                    "type": "expire"
                  }
                }
              ]
            }
      script: |
        #!/usr/bin/env sh
        jx-registry create --app rewardops/mx-$(params.APP_NAME)

    # https://github.com/GoogleContainerTools/kaniko
    - name: build-and-push-docker
      image: gcr.io/kaniko-project/executor:v1.12.1-debug
      env:
        - name: NPM_TOKEN
          valueFrom:
            secretKeyRef:
              name: build-$(params.APP_NAME)
              key: 'NPM_TOKEN'
      envFrom:
        - secretRef:
            name: build-$(params.APP_NAME)
      resources:
        requests:
          cpu: 500m
          memory: 1000Mi
        limits:
          cpu: 2000m
          memory: 4000Mi
      script: |
        #!/bin/sh
        source .jx/variables.sh
        echo "APP_NAME = $APP_NAME"
        echo "VERSION = $VERSION"

        cp /tekton/creds-secrets/tekton-container-registry-auth/.dockerconfigjson /kaniko/.docker/config.json

        # Loop through environment variables and write them to a file
        printenv | while IFS='=' read -r name value; do
            # Print each environment variable in the format: key="value"
            echo "$name=\"$value\"" >> env_vars_flat.txt
        done

        echo ">>> Building PR mx-$(params.APP_NAME)"
        eval /kaniko/executor \
          --skip-unused-stages \
          --cache=true \
          --cache-repo=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/cache-mx-$(params.APP_NAME) \
          --cache-copy-layers \
          --cleanup \
          --context=/workspace/source \
          --dockerfile=apps/$(params.APP_NAME)/Dockerfile \
          --destination=$PUSH_CONTAINER_REGISTRY/$DOCKER_REGISTRY_ORG/mx-$(params.APP_NAME):$VERSION \
          --build-arg NPM_TOKEN="$NPM_TOKEN" \
          --build-arg ENV_VARS_CONTEXT=env_vars_flat.txt

    # https://github.com/jenkins-x-plugins/jx-preview
    - name: promote-preview
      image: ghcr.io/jenkins-x-plugins/jx-preview:0.1.0
      script: |
        #!/usr/bin/env sh
        source .jx/variables.sh
        jx preview create -f infra/preview/helmfile.yaml --debug --service mx-$(params.APP_NAME)
