apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: brakeman
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    ruby_brakeman task 
  workspaces:
    - name: source
      description: A workspace that let's you run ruby_brakeman.
  params:
    - name: BASE_IMAGE
      description: Latest pii_service image 
      type: string
      default: "016157711389.dkr.ecr.us-east-1.amazonaws.com/rewardops/pii_service:latest"
  steps:
    - name: brakeman
      image: $(params.BASE_IMAGE)
      script: |
        #!/bin/sh
        [ ! -d /config ] && mkdir /config && \
        cat << EOF > /config/pii-mapping.yml
        proxy_backend:
          mapping:
            - pii_hostname: pii-service
              api_upstream: qa-api.rewardops.io
        EOF
        /bin/sh scripts/ci/ruby_brakeman.sh

