apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ro-current-version
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Git
    tekton.dev/tags: git
    tekton.dev/displayName: "Fetch Current Release"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    This task fetches the current version from the latest tag in the repo.
  workspaces:
    - name: source
      description: A workspace that contains the fetched git repository.
  params:
    - name: IMAGE_LABEL
      description: app name
      type: string
      default: "aircanada"
    - name: BASE_IMAGE
      description: the image used where the git binary is
      type: string
      default: "docker.io/alpine/git:v2.26.2@sha256:23618034b0be9205d9cc0846eb711b12ba4c9b468efdd8a59aac1d7b1a23363f"
    - name: VERBOSE
      description: Log the commands that are executed during `git-clone`'s operation.
      type: string
      default: "false"
  results:
    - name: current-version
      description: Value of the current-version
  steps:
    - name: current-version
      image: $(params.BASE_IMAGE)
      script: |
        #!/usr/bin/env sh
        set -eu -o pipefail
        
        echo "$(params.VERBOSE)"
        
        if [[ "$(params.VERBOSE)" == "true" ]] ; then
          set -x
        fi

        env
        pwd
        git tag -l --sort=-version:refname|grep ^"$(params.IMAGE_LABEL)-v" | head -1
        
        CURRENT_VERSION=$(git tag -l --sort=-version:refname|grep ^"$(params.IMAGE_LABEL)-v" | head -1)
        
        echo -n "CURRENT VERSION = "
        echo -n "$CURRENT_VERSION" |tee /tekton/results/current-version
        


