apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: minitest
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    ruby_minitest task 
  workspaces:
    - name: source
      description: A workspace that let's you run ruby_minitest.
  params:
    - name: BASE_IMAGE
      description: Latest pangea_build image 
      type: string
      default: "016157711389.dkr.ecr.us-east-1.amazonaws.com/rewardops/pangea_build:latest"
  results:
    - name: minitest
      description: Run Tests
  steps:
    - name: minitest
      image: $(params.BASE_IMAGE)
      script: |
        #!/usr/bin/env bash
        set -x
        cd /workspace/pangea
        sleep 12s
        /bin/wait-for-it.sh localhost:5432
        ./scripts/ci/tekton_ruby_minitest.sh

  sidecars:
    - image: 016157711389.dkr.ecr.us-east-1.amazonaws.com/rewardops/postgres:12.9
      name: postgres
      env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
