apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ro-rspec
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    RSpec task 
  workspaces:
    - name: source
      description: A workspace that let's you run RSpec.
      volumeClaimTemplate:  # PVC created this way will be cleaned-up after TaskRun/PipelineRun completes!
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi
  params:
    - name: BASE_IMAGE
      description: Latest Pangea Development Image 
      type: string
      default: "016157711389.dkr.ecr.us-east-1.amazonaws.com/rewardops/pangea_build:latest"
  results:
    - name: ro-rspec
      description: Run Tests
  steps:
    - name: ro-rspec
      image: $(params.BASE_IMAGE)
      envFrom:
      - secretRef:
          name: pangea-ci
      script: |
        #!/usr/bin/env bash
        set -x
        source .jx/variables.sh
        
        export KNAPSACK_PRO_REPOSITORY_ADAPTER=git
        export KNAPSACK_PRO_PROJECT_DIR=/workspace/source
        echo "INDEX NUMBER == $KNAPSACK_PRO_CI_NODE_INDEX"
        sleep 10s
        ./scripts/ci/tekton_ruby_rspec.sh

  sidecars:
    - image: 016157711389.dkr.ecr.us-east-1.amazonaws.com/rewardops/postgres:12.9
      name: postgres
      env:
      - name: POSTGRES_USER
        value: postgres
      - name: POSTGRES_PASSWORD
        value: postgres
      
