apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: ro-current-version
  labels:
    app.kubernetes.io/version: "0.2"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Git
    tekton.dev/tags: git
    tekton.dev/displayName: "In-house variables"
    tekton.dev/platforms: "linux/amd64"
spec:
  description: >-
    Add/Replace vars to variables.sh.
  workspaces:
    - name: source
      description: A workspace that contains the fetched git repository.
  params:
    - name: IMAGE_LABEL
      description: app name
      type: string
      default: "default"
    - name: BASE_IMAGE
      description: the image used where the jx-variables binary is
      type: string
      default: "ghcr.io/jenkins-x/jx-boot:3.2.264"
    - name: VERBOSE
      description: Log the commands that are executed during `git-clone`'s operation.
      type: string
      default: "false"
  results:
    - name: ro-variables
      description: populate variables.sh
  steps:
    - name: ro-variables
      image: $(params.BASE_IMAGE)
      script: |
        #!/usr/bin/env sh

        if [[ "$(params.VERBOSE)" == "true" ]] ; then
          env
          set -x
        fi

        sleep infinity

        jx gitops variables
        jx gitops pr variables
        sed -i "s/^export APP_NAME=.*/export APP_NAME=\"$(params.IMAGE_LABEL)\"/" /workspace/source/.jx/variables.sh
        
        if [ -f /tekton/results/current-version ]; then
          echo "CURRENT_VERSION=$(cat /tekton/results/current-version)" >> /workspace/source/.jx/variables.sh
        fi

        if [ -f /tekton/results/next-version ]; then
          echo "SEMVER=$(cat /tekton/results/next-version)" >> /workspace/source/.jx/variables.sh
        fi

